project_name: cli
release:
  github:
    name: replicated
    owner: replicatedhq
brews:
- tap:
    name: homebrew-replicated
    owner: replicatedhq
  folder: HomebrewFormula
  install: bin.install "replicated"
  homepage: https://docs.replicated.com/reference/replicated-cli-installing
  description: "Package KOTS applications and manage releases, channels, customers and entitlements using a command-line interface."
builds:
- goos:
  - linux
  - darwin
  goarch:
  - amd64
  - "386"
  env:
   - CGO_ENABLED=0
  main: cli/main.go
  ldflags: -s -w
    -X github.com/replicatedhq/replicated/pkg/version.version={{.Version}}
    -X github.com/replicatedhq/replicated/pkg/version.gitSHA={{.FullCommit}}
    -X github.com/replicatedhq/replicated/pkg/version.buildTime={{.Date}}
    -extldflags "-static"
  flags: -tags netgo -installsuffix netgo
  binary: replicated
  hooks: {}
archives:
- format: tar.gz
  name_template: "{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  files:
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
build:
  hooks: {}
dockers:
  - dockerfile: deploy/Dockerfile
    image_templates:
      - "replicated/vendor-cli:latest"
      - "replicated/vendor-cli:{{ .Major }}"
      - "replicated/vendor-cli:{{ .Major }}.{{ .Minor }}"
      - "replicated/vendor-cli:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
