name: CI

on:
  push:
    paths:
    - '**'
    - '!**.md'
    - '!doc/**'
    - '!**.png'

jobs:
  pacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make pacts
        run: make pacts
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make test
        run: make test
        env:
          REPLICATED_API_ORIGIN: https://api.staging.replicated.com/vendor
          REPLICATED_ID_ORIGIN: https://id.staging.replicated.com
          VENDOR_USER_EMAIL: dex+qa@replicated.com
          VENDOR_USER_PASSWORD: ${{ secrets.VENDOR_USER_PASSWORD }}
          REPLICATED_API_TOKEN: ${{ secrets.REPLICATED_API_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make build
        run: make build
