name: Release CLI

on:
  create:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run:  docker login -u="$DOCKERHUB_DOCKER_USER" -p="$DOCKERHUB_DOCKER_PASS"
      env:
        DOCKERHUB_DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_DOCKER_PASS: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: run goreleaser
      run: curl -sL https://git.io/goreleaser | VERSION=v0.123.3 bash
