name: Release CLI

on:
  create:
    tags:
      - 'v*'

# many jobs copied from main.yml because GHA has no way to create cross-workflow dependencies
# and no really rock-solid way to use an `if` property to limit to tag creation
jobs:
  make-pacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make pacts
        run: make pacts
  make-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make test
        run: make test
        env:
          REPLICATED_API_ORIGIN: https://api.staging.replicated.com/vendor
          REPLICATED_ID_ORIGIN: https://id.staging.replicated.com
          VENDOR_USER_EMAIL: dex+qa@replicated.com
          VENDOR_USER_PASSWORD: ${{ secrets.VENDOR_USER_PASSWORD }}
          REPLICATED_API_TOKEN: ${{ secrets.REPLICATED_API_TOKEN }}
  make-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make build
        run: make build
  snyk-vuln:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  create-release:
    runs-on: ubuntu-latest
    needs:
      - make-pacts
      - make-tests
      - make-build
      - snyk-vuln
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run:  docker login -u="$DOCKERHUB_DOCKER_USER" -p="$DOCKERHUB_DOCKER_PASS"
      env:
        DOCKERHUB_DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_DOCKER_PASS: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: run goreleaser
      run: curl -sL https://git.io/goreleaser | VERSION=v0.123.3 bash
